### ISSUE TITLE
Unmarshal failing for some types

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/go-ssz#32]
There seems to be a panic occurring when some types are unmarshaled. 

Discussed with @rauljordan that we should enhance our spectest suite to perform a roundtrip test. 
Hopefully that will shine light on the issue and we can resolve it from there.

**Comment by katzdan** [comment]
Please re-open this issue.

**Comment by prestonvanloon** [comment]
@katzdan Can you add any details?

**Comment by katzdan** [comment]
Beacon chain service logs :

INFO: Invocation ID: 30a1a1a4-e7d5-478e-a780-f37d9fb9f3a7
INFO: Analysed target //beacon-chain:beacon-chain (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //beacon-chain:beacon-chain up-to-date:
  bazel-bin/beacon-chain/linux_amd64_stripped/beacon-chain
INFO: Elapsed time: 0.741s, Critical Path: 0.02s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/beacon-chain/linux_amd64_stripped/beacon-chain --clear-db '--datadir=/tmp/pINFO: Build completed successfully, 1 total action
2019/07/01 05:08:06 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
[2019-07-01 05:08:06]  INFO node: Using custom parameter configuration
[2019-07-01 05:08:06]  INFO node: Checking db path=/tmp/prysm-data/beaconchaindata
[2019-07-01 05:08:06]  INFO node: Fetching testnet cluster address endpoint=https://beta.prylabs.net/contract
[2019-07-01 05:08:09]  INFO node: Starting beacon node version=Git commit: Local build. Built at: Moments ago
[2019-07-01 05:08:09]  INFO registry: Starting 8 services: [*p2p.Server *powchain.Web3Service *attestation.Service *operations.Service *blockchain.ChainService *sync.Service *rpc.Service *prometheus.Service]
[2019-07-01 05:08:09]  INFO p2p: Starting service
[2019-07-01 05:08:10]  INFO powchain: Starting service endpoint=wss://goerli.prylabs.net/websocket
[2019-07-01 05:08:10]  INFO attestation: Starting service
[2019-07-01 05:08:10]  INFO operation: Starting service
[2019-07-01 05:08:10]  INFO blockchain: Waiting for ChainStart log from the Validator Deposit Contract to start the beacon chain...
[2019-07-01 05:08:10]  INFO sync: Starting service
[2019-07-01 05:08:10]  INFO rpc: Starting service
[2019-07-01 05:08:10]  INFO rpc: Listening on port port=4000
[2019-07-01 05:08:10]  WARN rpc: You are using an insecure gRPC connection! Provide a certificate and key to connect securely
[2019-07-01 05:08:10]  INFO prometheus: Starting service endpoint=:8080
panic: runtime error: slice bounds out of range

goroutine 263 [running]:
github.com/prysmaticlabs/go-ssz.makeStructUnmarshaler.func1(0xc000053690, 0xc0, 0x110, 0x13125c0, 0xc0001fc310, 0x199, 0x0, 0x2279ad0, 0x1355060, 0xc00038ac00)
        external/com_github_prysmaticlabs_go_ssz/unmarshal.go:359 +0xe10
github.com/prysmaticlabs/go-ssz.makePtrUnmarshaler.func1(0xc000053690, 0xc0, 0x110, 0x1355060, 0xc00016e0f0, 0x196, 0x0, 0x300, 0x2ae, 0x0)
        external/com_github_prysmaticlabs_go_ssz/unmarshal.go:378 +0x99
github.com/prysmaticlabs/go-ssz.Unmarshal(0xc000053690, 0xc0, 0x110, 0x113fd40, 0xc00016e0f0, 0xc000397f00, 0x196)
        external/com_github_prysmaticlabs_go_ssz/unmarshal.go:39 +0x38d
github.com/prysmaticlabs/prysm/beacon-chain/core/helpers.DecodeDepositInput(0xc000053680, 0xd0, 0x120, 0x9e834bc77e14bb58, 0x85407cf610805629, 0xa13529f24ebe93d4)
        beacon-chain/core/helpers/deposits.go:56 +0x2b2
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Web3Service).ProcessDepositLog(0xc00055b680, 0x9c704d2847bca002, 0xadcd662278f7db31, 0xb471a6a, 0xc000296080, 0x1, 0x4, 0xc000053200, 0x5a0, 0x5a0, ...)
        beacon-chain/powchain/log_processing.go:80 +0x171
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Web3Service).ProcessLog(0xc00055b680, 0x9c704d2847bca002, 0xadcd662278f7db31, 0xb471a6a, 0xc000296080, 0x1, 0x4, 0xc000053200, 0x5a0, 0x5a0, ...)
        beacon-chain/powchain/log_processing.go:48 +0x41f
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Web3Service).processPastLogs(0xc00055b680, 0xc000283200, 0x932c8ea904e23003)
        beacon-chain/powchain/log_processing.go:175 +0x20c
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Web3Service).run(0xc00055b680, 0xc0001e3980)
        beacon-chain/powchain/service.go:326 +0x460
created by github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Web3Service).Start
        beacon-chain/powchain/service.go:165 +0x1a7

**Comment by rauljordan** [comment]
This has been fixed by #33

**Comment by katzdan** [comment]
After updating to the latest commit (as of now) I'm still getting panics in the beacon-chain.

[2019-07-03 05:31:10]  INFO node: Using custom parameter configuration
[2019-07-03 05:31:10]  INFO node: Checking db path=/tmp/prysm-data/beaconchaindata
[2019-07-03 05:31:10]  INFO node: Fetching testnet cluster address endpoint=https://beta.prylabs.net/contract
[2019-07-03 05:31:13]  INFO node: Starting beacon node version=Git commit: Local build. Built at: Moments ago
[2019-07-03 05:31:13]  INFO registry: Starting 8 services: [*p2p.Server *powchain.Web3Service *attestation.Service *operations.Service *blockchain.ChainService *sync.Service *rpc.Service *prometheus.Service]
[2019-07-03 05:31:13]  INFO p2p: Starting service
[2019-07-03 05:31:15]  INFO powchain: Starting service endpoint=wss://goerli.prylabs.net/websocket
[2019-07-03 05:31:15]  INFO attestation: Starting service
[2019-07-03 05:31:15]  INFO operation: Starting service
[2019-07-03 05:31:15]  INFO blockchain: Waiting for ChainStart log from the Validator Deposit Contract to start the beacon chain...
[2019-07-03 05:31:15]  INFO sync: Starting service
[2019-07-03 05:31:15]  INFO rpc: Starting service
[2019-07-03 05:31:15]  INFO rpc: Listening on port port=4000
[2019-07-03 05:31:15]  WARN rpc: You are using an insecure gRPC connection! Provide a certificate and key to connect securely
[2019-07-03 05:31:15]  INFO prometheus: Starting service endpoint=:8080
panic: runtime error: slice bounds out of range

goroutine 290 [running]:
github.com/prysmaticlabs/go-ssz.makeStructUnmarshaler.func1(0xc000302490, 0xc0, 0x110, 0x1312b80, 0xc0000fe7e0, 0x199, 0x0, 0x2279ad0, 0x1355620, 0xc0004830e0)
        external/com_github_prysmaticlabs_go_ssz/unmarshal.go:388 +0xe10
github.com/prysmaticlabs/go-ssz.makePtrUnmarshaler.func1(0xc000302490, 0xc0, 0x110, 0x1355620, 0xc000188130, 0x196, 0x0, 0x300, 0x2ae, 0x0)
        external/com_github_prysmaticlabs_go_ssz/unmarshal.go:407 +0x99
github.com/prysmaticlabs/go-ssz.Unmarshal(0xc000302490, 0xc0, 0x110, 0x1140300, 0xc000188130, 0xc0004825a0, 0x196)
        external/com_github_prysmaticlabs_go_ssz/unmarshal.go:39 +0x38d
github.com/prysmaticlabs/prysm/beacon-chain/core/helpers.DecodeDepositInput(0xc000302480, 0xd0, 0x120, 0x9e834bc77e14bb58, 0x85407cf610805629, 0xa13529f24ebe93d4)
        beacon-chain/core/helpers/deposits.go:56 +0x2b2
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Web3Service).ProcessDepositLog(0xc00051c300, 0x9c704d2847bca002, 0xadcd662278f7db31, 0xb471a6a, 0xc0004b4100, 0x1, 0x4, 0xc000302000, 0x5a0, 0x5a0, ...)
        beacon-chain/powchain/log_processing.go:80 +0x171
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Web3Service).ProcessLog(0xc00051c300, 0x9c704d2847bca002, 0xadcd662278f7db31, 0xb471a6a, 0xc0004b4100, 0x1, 0x4, 0xc000302000, 0x5a0, 0x5a0, ...)
        beacon-chain/powchain/log_processing.go:48 +0x41f
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Web3Service).processPastLogs(0xc00051c300, 0xc0000bc900, 0x57095efb0f1d4b88)
        beacon-chain/powchain/log_processing.go:175 +0x20c
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Web3Service).run(0xc00051c300, 0xc0000486c0)
        beacon-chain/powchain/service.go:326 +0x460
created by github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Web3Service).Start
        beacon-chain/powchain/service.go:165 +0x1a7

**Comment by rauljordan** [comment]
Resolved by #41
